name: deploy-website

# Only run this when the main branch changes
on:
  workflow_dispatch:
  push:

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.6

    - name: Install dependencies
      run: |
        pip install ablog
    # Build the book
    - name: Build the site
      run: |
        ablog build
    # Push the book's HTML to github-pages
    - name: Pushes to another repository
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: '_website'
        destination-github-username: 'famosab'
        destination-repository-name: 'famosab.github.io'
        user-email: famke.baeuerle@gmail.com
